// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BiolatencyHist struct {
	_     structs.HostLayout
	Slots [20]uint64
}

type BiolatencyReqKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BiolatencyMapIoLat                  = "io_lat"
	BiolatencyMapStartReq               = "start_req"
	BiolatencyProgHandleBlockRqComplete = "handle_block_rq_complete"
	BiolatencyProgHandleBlockRqIssue    = "handle_block_rq_issue"
)

// LoadBiolatency returns the embedded CollectionSpec for Biolatency.
func LoadBiolatency() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BiolatencyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Biolatency: %w", err)
	}

	return spec, err
}

// LoadBiolatencyObjects loads Biolatency and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BiolatencyObjects
//	*BiolatencyPrograms
//	*BiolatencyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBiolatencyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBiolatency()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BiolatencySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BiolatencySpecs struct {
	BiolatencyProgramSpecs
	BiolatencyMapSpecs
	BiolatencyVariableSpecs
}

// BiolatencyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BiolatencyProgramSpecs struct {
	HandleBlockRqComplete *ebpf.ProgramSpec `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.ProgramSpec `ebpf:"handle_block_rq_issue"`
}

// BiolatencyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BiolatencyMapSpecs struct {
	IoLat    *ebpf.MapSpec `ebpf:"io_lat"`
	StartReq *ebpf.MapSpec `ebpf:"start_req"`
}

// BiolatencyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BiolatencyVariableSpecs struct {
}

// BiolatencyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBiolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type BiolatencyObjects struct {
	BiolatencyPrograms
	BiolatencyMaps
	BiolatencyVariables
}

func (o *BiolatencyObjects) Close() error {
	return _BiolatencyClose(
		&o.BiolatencyPrograms,
		&o.BiolatencyMaps,
	)
}

// BiolatencyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBiolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type BiolatencyMaps struct {
	IoLat    *ebpf.Map `ebpf:"io_lat"`
	StartReq *ebpf.Map `ebpf:"start_req"`
}

func (m *BiolatencyMaps) Close() error {
	return _BiolatencyClose(
		m.IoLat,
		m.StartReq,
	)
}

// BiolatencyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBiolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type BiolatencyVariables struct {
}

// BiolatencyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBiolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type BiolatencyPrograms struct {
	HandleBlockRqComplete *ebpf.Program `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.Program `ebpf:"handle_block_rq_issue"`
}

func (p *BiolatencyPrograms) Close() error {
	return _BiolatencyClose(
		p.HandleBlockRqComplete,
		p.HandleBlockRqIssue,
	)
}

func _BiolatencyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed biolatency_x86_bpfel.o
var _BiolatencyBytes []byte
