// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ExecsnoopMapExecEvents              = "exec_events"
	ExecsnoopProgHandleSchedProcessExec = "handle_sched_process_exec"
)

// LoadExecsnoop returns the embedded CollectionSpec for Execsnoop.
func LoadExecsnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecsnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Execsnoop: %w", err)
	}

	return spec, err
}

// LoadExecsnoopObjects loads Execsnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecsnoopObjects
//	*ExecsnoopPrograms
//	*ExecsnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecsnoopObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecsnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecsnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecsnoopSpecs struct {
	ExecsnoopProgramSpecs
	ExecsnoopMapSpecs
	ExecsnoopVariableSpecs
}

// ExecsnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecsnoopProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
}

// ExecsnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecsnoopMapSpecs struct {
	ExecEvents *ebpf.MapSpec `ebpf:"exec_events"`
}

// ExecsnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecsnoopVariableSpecs struct {
}

// ExecsnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecsnoopObjects struct {
	ExecsnoopPrograms
	ExecsnoopMaps
	ExecsnoopVariables
}

func (o *ExecsnoopObjects) Close() error {
	return _ExecsnoopClose(
		&o.ExecsnoopPrograms,
		&o.ExecsnoopMaps,
	)
}

// ExecsnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecsnoopMaps struct {
	ExecEvents *ebpf.Map `ebpf:"exec_events"`
}

func (m *ExecsnoopMaps) Close() error {
	return _ExecsnoopClose(
		m.ExecEvents,
	)
}

// ExecsnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecsnoopVariables struct {
}

// ExecsnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecsnoopPrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
}

func (p *ExecsnoopPrograms) Close() error {
	return _ExecsnoopClose(
		p.HandleSchedProcessExec,
	)
}

func _ExecsnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execsnoop_x86_bpfel.o
var _ExecsnoopBytes []byte
