// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RunqlatHist struct {
	_     structs.HostLayout
	Slots [20]uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RunqlatMapRunqLat            = "runq_lat"
	RunqlatMapStart              = "start"
	RunqlatProgHandleSchedSwitch = "handle_sched_switch"
	RunqlatProgHandleSchedWakeup = "handle_sched_wakeup"
)

// LoadRunqlat returns the embedded CollectionSpec for Runqlat.
func LoadRunqlat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RunqlatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Runqlat: %w", err)
	}

	return spec, err
}

// LoadRunqlatObjects loads Runqlat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RunqlatObjects
//	*RunqlatPrograms
//	*RunqlatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRunqlatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRunqlat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RunqlatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqlatSpecs struct {
	RunqlatProgramSpecs
	RunqlatMapSpecs
	RunqlatVariableSpecs
}

// RunqlatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqlatProgramSpecs struct {
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
}

// RunqlatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqlatMapSpecs struct {
	RunqLat *ebpf.MapSpec `ebpf:"runq_lat"`
	Start   *ebpf.MapSpec `ebpf:"start"`
}

// RunqlatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqlatVariableSpecs struct {
}

// RunqlatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqlatObjects struct {
	RunqlatPrograms
	RunqlatMaps
	RunqlatVariables
}

func (o *RunqlatObjects) Close() error {
	return _RunqlatClose(
		&o.RunqlatPrograms,
		&o.RunqlatMaps,
	)
}

// RunqlatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqlatMaps struct {
	RunqLat *ebpf.Map `ebpf:"runq_lat"`
	Start   *ebpf.Map `ebpf:"start"`
}

func (m *RunqlatMaps) Close() error {
	return _RunqlatClose(
		m.RunqLat,
		m.Start,
	)
}

// RunqlatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqlatVariables struct {
}

// RunqlatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqlatPrograms struct {
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.Program `ebpf:"handle_sched_wakeup"`
}

func (p *RunqlatPrograms) Close() error {
	return _RunqlatClose(
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
	)
}

func _RunqlatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runqlat_x86_bpfel.o
var _RunqlatBytes []byte
